#!/bin/bash

set -e

if [ -f ./node_modules/.bin/eslint ]; then
    COMMAND=./node_modules/.bin/eslint
else
    echo "No local installation of eslint found, installing eslint... " >&2
    npm install -g eslint >&2
    COMMAND=$(which eslint)
fi

rm -f /tmp/analysis_result_eslint

echo "Running $COMMAND --format checkstyle $@">&2

$COMMAND --debug --color --format checkstyle --output-file=./tmp/analysis_result_eslint "$@" >&2


cat ./tmp/analysis_result_eslint

